#
# application name
#
appName: TEST_APP

#
# All hosts for this application
#
appHosts:
  - http://host1.com
  - http://host2.com
  - http://host3.com
  - http://host4.com

#
# Available balancing modes are:
# ROUND_ROBIN, RANDOM, KEY_HASH, IP_HASH, STICKY
#
appBalancingMode: ROUND_ROBIN

#
# If balancing mode is KEY_HASH define your key
# otherwise set to an empty table
#
keysForRoute:
  - a
  - b
  - c

# set it to true is xbalancer is behind the load balancer
isLoadBalanced: false