#######################################################################
## server config
#######################################################################
server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG

  # Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
  # Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
  # Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/xbalancer-app.log
      archivedLogFilenamePattern: /tmp/xbalancer-app-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MiB

#######################################################################
# application config
#######################################################################

#
# application name
#
appName: TEST_APP

#
# All hosts for this application
#
appHosts:
  - http://host1.com
  - http://host2.com
  - http://host3.com
  - http://host4.com

#
# Available balancing modes are:
# ROUND_ROBIN, RANDOM, KEY_HASH, IP_HASH, STICKY, TIMESTAMP_HASH, WEIGHTED
#
appBalancingMode: WEIGHTED

#
# If balancing mode is KEY_HASH define your keys here
# otherwise set to an empty array []
# Keys are parameter names from the http request. Their values will be used to
# calculate the fingerprint which will be associated with the host.
#
keysForRoute:
  - a
  - b
  - c

#
# If balancing mode is WEIGHTED define your weights here
# otherwise set to an empty array []
# Their values are counted as 100% of traffic.
# You can distribute your traffic among the hosts here (the same order as hosts)
#
weights:
  - 2
  - 4
  - 1
  - 3

# set it to true is xbalancer is behind the load balancer
isLoadBalanced: false
