#######################################################################
## server config
#######################################################################
server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

#######################################################################
# application config
#######################################################################

#
# application name
#
appName: TEST_APP

#
# All hosts for this application
#
appHosts:
  - http://host1.com
  - http://host2.com
  - http://host3.com
  - http://host4.com

#
# Available balancing modes are:
# ROUND_ROBIN, RANDOM, KEY_HASH, IP_HASH, STICKY, TIMESTAMP_HASH
#
appBalancingMode: ROUND_ROBIN

#
# If balancing mode is KEY_HASH define your keys here
# otherwise set to an empty array []
#
keysForRoute:
  - a
  - b
  - c

# set it to true is xbalancer is behind the load balancer
isLoadBalanced: false
